### ISSUE TITLE
consider adding Shapley decomposition for inequality measures

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#256]

**Comment by DjalmaPessoa** [comment]
Guilherme, would it be possible to include a section on decomposition in the book? 
There is some discussion at IBGE to use it with PNADC data.
It is not clear what type of decomposition they want, but if they specify,  perhaps we might include in convey?

**Comment by ajdamico** [comment]
djalma, last night guilherme and i discussed keeping most decomposition
measures together alongside their main functions (like chapter 3.8) -- and
not separated into a single section of decompositions.  do you think that's
a bad idea?  one alternative would be to add a brief section in chapter 1
that generally describes decompositions, and then keep each svy*dec()
function alongside it's respective function?

**Comment by DjalmaPessoa** [comment]
I believe it is ok to keep alongside their main functions but adding more functions the produce decompositions.
Also, possibly  stressing  the subject matter aspects rather than only the satistical part, making the book more palatable to the potential users of convey (economists). 
This is a job for the super Guilherme.

**Comment by ajdamico** [comment]
is this an important addition to `convey` or do you think we could close it?
