### ISSUE TITLE
create replication vignette for svyarpr

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#372]
# matches
	attr(svyarpr(~ eqincome , des_eusilc_ultimate_cluster) , 'var') * 10000

	##            eqincome
	## eqincome 0.07586194

	varpoord_arpr_calculation$all_result$var

	## [1] 0.08718569

	# matches
	varpoord_arpr_calculation$all_result$se

	## [1] 0.2952722

	SE(svyarpr(~ eqincome , des_eusilc_ultimate_cluster)) * 100

	##           eqincome
	## eqincome 0.2754305

**Comment by guilhermejacob** [comment]
To understand why the estimates differ, notice that arpr1lin is the *domain* poverty rate assuming we know the poverty threshold, defined over the entire 
Now, Fprime works like a derivative of the *domain* poverty rate wrt the *full sample* estimated threshold. It "propagates" the uncertainty expressed in arptlin over to the arprlin.

This highlights three issues:

1. The domain indicator should be used only for the domain poverty rate term, as observations outside the domain still influence the ARPT estimation.
2. Fprime should be computed on the domain sample, since we are interested in the impact on the domain poverty rate;
3. Fprime is the derivative wrt to the estimated threshold, not the estimated quantile.

The issue on (3) is the reason why convey differs from vardpoor here.
We sent them a PR in 2022. This commit should solve this: https://github.com/CSBLatvia/vardpoor/compare/master...ajdamico:vardpoor:patch-1.

**Comment by ajdamico** [comment]
fixed at https://github.com/guilhermejacob/context/pull/20

**Comment by ajdamico** [comment]
apologies, i might be forgetting what we had discussed previously..

this branch is still open and these changes haven't been incorporated:

https://github.com/ajdamico/convey/compare/master...issue-372

did we mean to make this edit?  it's not currently part of the master branch..

**Comment by guilhermejacob** [comment]
No, it just reproduces numbers on `vardpoor`. But, as discussed, I believe our estimator seems closer to what Osier (2009) wrote.
But I do think the branch should be kept for reproducibility/discussion purposes.

**Comment by ajdamico** [comment]
i've included comments of the differences in the master branch
https://github.com/ajdamico/convey/pull/423
