### ISSUE TITLE
potential edits to svyqsr text section?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#373]
1. the vardpoor library only allows one alpha parameter (https://rdrr.io/cran/vardpoor/src/R/linqsr.R), does that mean it's not possible to calculate the palma ratio with it?

2. if i'm reading things correctly, i think the palma ratio would use `alpha1 = 0.1` and `alpha2 = 0.6` rather than `alpha2 = 0.4`.  is that correct?  i think using 0.4 instead of 0.6 would be an easy mistake for users to make, it might make sense to list those parameters directly in the text?

**Comment by guilhermejacob** [comment]
Ok, let's see:

1. No, you won't be able to compute the Palma ratio with those.
2. There are actually two ways to compute the Palma ratio. One is using `svyqsr` and the other is using `svylorenz` (they won't match exactly because of different estimators, but are asymptotically equal). The Palma ratio is the top 10% divided by the bottom 40%. In `svyqsr`, this means `alpha1 = .40` and `alpha2 = .90`. Remember that, inside `svyqsr`, `alpha2` works with `svyisq( upper = TRUE )`; that means that we will compute the total and subtract the bottom `alpha2`% to get the top `(1 - alpha2)`%.

**Comment by ajdamico** [comment]
would you be willing to incorporate my questions and your responses into the text?  i could try if you don't have time
