### ISSUE TITLE
svyarpr text says numbers match where they don't

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#386]
if i'm understanding correctly, the new numbers in this changeset make the statement that vardpoor matches convey for linearized designs no longer true ?

https://github.com/guilhermejacob/context/pull/23/files#diff-91dbc690af363b1d2d087e78fec174a76a0437df7150b2d5808dbc4fcdac09f9

**Comment by guilhermejacob** [comment]
Ah, yes. The linearization-based variance estimators are different, so they no longer match.

**Comment by ajdamico** [comment]
i can fix but just checking:  for the same reason as mentioned here?

https://github.com/guilhermejacob/context/blob/master/01-poverty.Rmd#L313

**Comment by guilhermejacob** [comment]
I see... I think I built the book with my "patched" `vardpoor`. I'll rebuild it again now with the CRAN version.

**Comment by guilhermejacob** [comment]
Or you could do it to avoid a merge mess, @ajdamico ;)

**Comment by ajdamico** [comment]
for sure!  could you just give me one sentence explaining why the linearization-based variance estimators should differ from vardpoor?  i had previously thought the estimates only differed on replication designs..

**Comment by guilhermejacob** [comment]
Discussed at length [here](https://github.com/ajdamico/convey/issues/372#issuecomment-1656264143), but  possible one liners:

- Because Fprime is the derivative wrt to the estimated threshold, not the estimated quantile (point to Osier);
- Because our linearization results differ (point to issue).

For the usual reader, the second should do, but the first is more helpful, I think.
